version: '3.5'
services:
  portal:
    image: nginx:alpine
    container_name: arkid-portal
    restart: always
    environment:
      - TZ=Asia/Shanghai
    networks:
      - arkid
    ports:
      - 8989:80
    depends_on:
      - be
      - fe
    volumes:
      - ./portal.conf:/etc/nginx/conf.d/default.conf
  be:
    image: "registry.cn-zhangjiakou.aliyuncs.com/ark-releases/arkid:2.5.14"
    container_name: arkid-be
    sysctls:
      - net.core.somaxconn=65535
    restart: always
    working_dir: /arkid
    entrypoint: sh -c "tail -f /dev/null"
    environment:
      - TZ=Asia/Shanghai
      - K8SORDC='true'
      - REDIS_HOST=arkid-redis
    networks:
      - arkid
    volumes:
      - ../:/arkid
      - ./arkid.toml:/arkid/arkid.local.toml
      - ./settings.py:/arkid/settings_local.py
      - ./supervisor.conf:/arkid/supervisord.conf
  fe:
    image: "registry.cn-zhangjiakou.aliyuncs.com/ark-releases/arkid-fe:2.5.14"
    container_name: arkid-fe
    restart: always
    environment:
      - TZ=Asia/Shanghai
    networks:
      - arkid
    volumes:
      - ./fe.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis:5.0.3
    container_name: arkid-redis
    restart: always
    environment:
      - TZ=Asia/Shanghai
    networks:
      - arkid
networks:
  arkid:
    name: arkid
    driver: bridge
