name: arkid v2 cicd

on:
  push:
    branches:
      - main
jobs:
  dev2test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login harbor
      uses: docker/login-action@v1 
      with:
        registry: harbor.longguikeji.com
        username: ${{ secrets.HARBORUSER }}
        password: ${{ secrets.HARBORPWD }}
    - id: get-short-id
      run: |
        id=$(echo ${{github.sha}})
        echo "::set-output name=id::${id: 0 :8}"
    - run: echo "${{steps.get-short-id.outputs.id}}"
    - id: set-pip
      run: |
        sed -i "s@https://mirrors.aliyun.com/pypi/simple@https://pypi.python.org/simple@g" requirements.txt;
        sed -i "s@https://mirrors.aliyun.com/pypi/simple@https://pypi.python.org/simple@g" requirements-dev.txt;
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        build-args: |
          DEBIAN=http://deb.debian.org/debian
          DEBIANSRT=http://security.debian.org/debian-security
          PIP="-i https://pypi.python.org/simple"
        push: true
        tags: |
          harbor.longguikeji.com/ark-releases/arkid:v2dev-farasis-${{ github.run_number }}
