name: mkdocs
on:
  push:
    branches:
      - v2.5-dev 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: wget http://xmlsoft.org/sources/libxml2-2.9.1.tar.gz
      - run: tar -xvf libxml2-2.9.1.tar.gz
      - run: ./libxml2-2.9.1/configure && make && make install
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
